### PR TITLE
SoQt -> Quarter

### PR DESCRIPTION
**Pull request by sanguinariojoe**
The way this works is first instructing CMake to look for Quarter, and if it is not found, it looks for SoQt as a fallback method. To this end I hijacked the definition SOQT_DLL, whcih maybe you do not like @kmoks . Of course we can change that.

If SoQt fallback is considered, nothing is theoretically changing. However, if Quarter is found, then a new class called FdQuarterViewer is added, which is indeed [impersonating the SoQtViewer](https://github.com/kmoks/fedem-gui/compare/qt6-port...core-marine-dev:fedem-gui:qt6-quarter?expand=1#diff-d8572c1866b5a03af3ecaab382cc8abf808308652f0f3389b5588521bfd97058R315)

I am not really used to Fedem, so i suspect a lot of stuff stopped working. So I suppose I need to ask you @kmoks to test it and give me feedback.

### CODE REVIEW

**Comment by kmoks** [comment]
I looked at your PR now @sanguinariojoe , and did some minor changes (see HEAD commit on my [qt6-quarter](https://github.com/kmoks/fedem-gui/tree/qt6-quarter) branch:

- Added a static function `FdViewer::create()` returning a `FFuComponentBase` pointer, to limit the dependency on SoQt/Quarter to the vpmDisplay library only.
- Then we don't need to search for Quarter/SoQt in the top-level CMakeLists.txt
- Removed search for Quarter on windows. We'll add that later after/if we get it working on Linux.
- Added a cmake option USE_QUARTER such that it is possible to choose which package to use in case you have both installed.

I managed to build this on my Linux system using the Quarter library (which I first built myself from the 1.2.1 sources). Although it runs, we are not there yet. As most of the commands for manipulating the 3D view are not working, like zoom, pan and rotate using the mouse, predefined view buttons, etc. So far I only found that using the arrow keys on the keyboard works, for panning the view one step sideways or up and down. Maybe your new class FdQuarterViewer needs some more functionality? I did not look at your implementation details there yet.

**Comment by sanguinariojoe** [comment]
Yeah, that' what I suspected, but I did not know for sure since you have a lot of event handling.

Do not panic, it is probably easy to fix.

The first possible problem is we need to call `viewer->setNavigationModeFile(QUrl("coin:///scxml/navigation/examiner.xml"));` at some point (see the basic Quarter example [here](https://www.coin3d.org/Quarter/html/),). However, I tried to add it on a random place, and it did not work. Probably it should be done after setting the root scene.

Another possibility is that the event() -> FdQtViewer::processEvent() -> FdQuarterViewer::processEvent() -> event()  system I figured out is not working.

So what I am doing is testing the impersonation on a simpler problem and fix it there. Then I move to the actual code

**Comment by sanguinariojoe** [comment]
Well, I recovered some functionality! Now the mouse wheel seems to do zoom ok, and the middle and right button sets the cursor. They do not rotate or pan though

It is quite strange, because if I track when the Quarter processSoEvent() is called, everything seems right. Maybe some callback is blocking it?

To be continued...

**Comment by sanguinariojoe** [comment]
I see you already cherry-picked this on your qt6-quarter branch, so I am closing this and continue from there

**Pull request closed without merging**
